### ISSUE TITLE
Simulation states match will take over 100 rounds to complete.

### ISSUE THREAD

**Issue by CTOUT** [Kreolix/CovenantMissionHelper#15]
Mission: - 
Terrorwings on High

Adventurer combination/positions: -
Master Sha'Lor - Chalkyth - Te'zan
	Dreamweaver - Niya

Addon message: -
More than 100 rounds.  Winner is undefined.

![Terrorwings](https://user-images.githubusercontent.com/22860918/105625405-03771680-5e21-11eb-8fc8-d3762edcc61a.png)

If I switch Master Sha'Lor and Niya around, it's a predicted win after 2 rounds.

**Comment by CTOUT** [comment]
It appears that the mission would actually be successful, but the last mob is killed by a DOT and doesn't appear as "defeated" in the log, hence the addon keeps simulating what happens if the party has no opponents.
![Terrorwings2](https://user-images.githubusercontent.com/22860918/105625495-a7f95880-5e21-11eb-903d-99ca58988870.png)
![Terrorwings3](https://user-images.githubusercontent.com/22860918/105625498-aa5bb280-5e21-11eb-80e1-da9055e67982.png)

**Comment by Kreolix** [comment]
Same as #7 
fixed in 3.0.0 #16
