### ISSUE TITLE
'Optimize' Lua error

### ISSUE THREAD

**Issue by reaper666735** [Kreolix/CovenantMissionHelper#17]
Hello,

just downloaded your addon and when i tried the "Optimize" button i get this Lua error:

1x CovenantMissionHelper\Board.lua:331: attempt to index field '?' (a nil value)
[string "@CovenantMissionHelper\Board.lua"]:331: in function `onUnitTakeDamage'
[string "@CovenantMissionHelper\Board.lua"]:296: in function `makeUnitAction'
[string "@CovenantMissionHelper\Board.lua"]:161: in function `fight'
[string "@CovenantMissionHelper\Board.lua"]:142: in function `simulate'
[string "@CovenantMissionHelper\MetaBoard.lua"]:46: in function `findBestDisposition'
[string "@CovenantMissionHelper\CovenantMissionHelper-0.1.lua"]:55: in function `findBestDisposition'
[string "@CovenantMissionHelper\UI.lua"]:94: in function <CovenantMissionHelper\UI.lua:93>

Locals:
self = <table> {
 hasRandomSpells = false
 initialEnemiesHP = 6920
 initialAlliesHP = 4740
 units = <table> {
 }
 isEmpty = false
 max_rounds = 100
 missionID = 2201
 isMissionOver = false
 isCalcRandom = false
 winXP = 1600
 baseXP = 400
 probability = 100
}
spellID = 11
casterBoardIndex = <table> {
 isAutoTroop = false
 followerGUID = "0x0000000025003044"
 role = 1
 maxHealth = 1320
 spells = <table> {
 }
 boardIndex = 2
 untargetable = false
 currentHealth = 694
 isLoseLvlUp = false
 name = "Kleia"
 isWinLvlUp = true
 ID = 1260
 buffs = <table> {
 }
 reflect = 33
 attack = 132
}
eventTargetInfo = <table> {
 oldHealth = 9
 boardIndex = 6
 points = 33
 maxHealth = 2640
 newHealth = 0
}
(*temporary) = <function> defined @CovenantMissionHelper\CovenantMissionHelper.lua:154
(*temporary) = <table> {
 Spell = <table> {
 }
 Buff = <table> {
 }
 Unit = <table> {
 }
 log = <function> defined @CovenantMissionHelper\CovenantMissionHelper.lua:154
 debug_log = <function> defined @CovenantMissionHelper\CovenantMissionHelper.lua:159
 MetaBoard = <table> {
 }
 TargetManager = <table> {
 }
 DataTables = <table> {
 }
 Board = <table> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "|cFFFF7700 %s kill %s |r"
(*temporary) = nil
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by reaper666735** [comment]
another bug when you use "Troops" in the battle 

4x CovenantMissionHelper\Board.lua:99: attempt to perform arithmetic on field 'xp' (a nil value)
[string "@CovenantMissionHelper\Board.lua"]:99: in function `new'
[string "@CovenantMissionHelper\CovenantMissionHelper-0.1.lua"]:29: in function <...dOns\CovenantMissionHelper\CovenantMissionHelper.lua:25>
[string "@CovenantMissionHelper\CovenantMissionHelper-0.1.lua"]:37: in function `simulateFight'
[string "@CovenantMissionHelper\CovenantMissionHelper-0.1.lua"]:20: in function <...dOns\CovenantMissionHelper\CovenantMissionHelper.lua:15>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UpdateAllyPower'
[string "@Blizzard_GarrisonUI\Blizzard_CovenantMissionUI.lua"]:647: in function `AssignFollowerToMission'
[string "@Blizzard_GarrisonUI\Blizzard_CovenantMissionUI.lua"]:472: in function `ptr'
[string "@SharedXML\CallbackRegistry.lua"]:55: in function `TriggerEvent'
[string "@Blizzard_GarrisonUI\Blizzard_AdventuresPuck.lua"]:426: in function <...dOns\Blizzard_GarrisonUI\Blizzard_AdventuresPuck.lua:423>

Locals:
self = <table> {
 checkMissionOver = <function> defined @CovenantMissionHelper\Board.lua:186
 Errors = <table> {
 }
 constructResultString = <function> defined @CovenantMissionHelper\Board.lua:382
 getTargetIndexes = <function> defined @CovenantMissionHelper\Board.lua:410
 simulate = <function> defined @CovenantMissionHelper\Board.lua:123
 onUnitTakeDamage = <function> defined @CovenantMissionHelper\Board.lua:328
 getTurnOrder = <function> defined @CovenantMissionHelper\Board.lua:227
 isTargetableUnit = <function> defined @CovenantMissionHelper\Board.lua:214
 new = <function> defined @CovenantMissionHelper\Board.lua:38
 makeUnitAction = <function> defined @CovenantMissionHelper\Board.lua:253
 CombatLogEvents = <table> {
 }
 getTargetableUnits = <function> defined @CovenantMissionHelper\Board.lua:218
 __index = <table> {
 }
 HiddenCombatLog = <table> {
 }
 getTotalLostHP = <function> defined @CovenantMissionHelper\Board.lua:336
 isWin = <function> defined @CovenantMissionHelper\Board.lua:401
 CombatLog = <table> {
 }
 getMyTeam = <function> defined @CovenantMissionHelper\Board.lua:353
 manageBuffsFromDeadUnits = <function> defined @CovenantMissionHelper\Board.lua:316
 fight = <function> defined @CovenantMissionHelper\Board.lua:145
 manageAppliedBuffs = <function> defined @CovenantMissionHelper\Board.lua:302
 setHasRandomSpells = <function> defined @CovenantMissionHelper\Board.lua:169
 isUnitAlive = <function> defined @CovenantMissionHelper\Board.lua:206
}
missionPage = <unnamed> {
 EncounterIcon = <unnamed> {
 }
 StartMissionFrame = <unnamed> {
 }
 CostFrame = <unnamed> {
 }
 mentorLevel = 0
 StartMissionButton = <unnamed> {
 }
 SetFollowerListSortFuncsForMission = <function> defined @Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1356
 mentorItemLevel = 0
 FollowerBackground = <unnamed> {
 }
 IconBG = <unnamed> {
 }
 Stage = <unnamed> {
 }
 UpdateFollowerModel = <function> defined @Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1361
 missionEffects = <table> {
 }
 lastUpdate = 8327.086000
 EmptyString = <unnamed> {
 }
 GetFollowerFrameFromID = <function> defined @Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1384
 CalculateDurabilityLoss = <function> defined @Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1432
 EnemyBackground = <unnamed> {
 }
 missionInfo = <table> {
 }
 UpdatePortraitPulse = <function> defined @Blizzard_GarrisonUI\Blizzard_CovenantMissionUI.lua:964
 UpdateEmptyString = <function> defined @Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1376
 Board = <unnamed> {
 }
 SetCounters = <function> defined @Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1352
 0 = <userdata>
 CheckCounter = <function> defined @Blizzard_GarrisonTemplates\Blizzard_GarrisonMissionTemplates.lua:2322
 BoardDropShadow = <unnamed> {
 }
 CloseButton = <unnamed> {
 }
 NineSlice = <unnamed> {
 }
 AddFollower = <function> defined @Blizzard_GarrisonUI\Blizzard_CovenantMissionUI.lua:948
 UpdateFollowerDurability = <function> defined @Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1442
 ItemLevelHitboxFrame = <unnamed> {
 }
 GenerateSuccessTooltip = <function> defined @Blizzard_GarrisonTemplates\Blizzard_GarrisonMissionTemplates.lua:2318
 Median = <unnamed> {
 }
}
isCalcRandom = false
newObj = <table> {
 hasRandomSpells = false
 initialEnemiesHP = 1392
 isEmpty = true
 units = <table> {
 }
 initialAlliesHP = 0
 max_rounds = 100
 missionID = 2168
 baseXP = 100
 isCalcRandom = false
 winXP = 100
 isMissionOver = false
 probability = 100
}
isCompletedMission = false
missionInfo = <table> {
 description = "The problem has gotten even

**Comment by Amaalaa** [comment]
_have the same issue I think. Night Fae. This is when I select optimize. I also get a lua message when I add my troops. will post that in another comment.
 _
Message: Interface\AddOns\CovenantMissionHelper\Board.lua:99: attempt to perform arithmetic on field 'xp' (a nil value)
Time: Sun Jan 24 11:29:00 2021
Count: 3
Stack: Interface\AddOns\CovenantMissionHelper\Board.lua:99: attempt to perform arithmetic on field 'xp' (a nil value)
[string "@Interface\AddOns\CovenantMissionHelper\Board.lua"]:99: in function `new'
[string "@Interface\AddOns\CovenantMissionHelper\MetaBoard.lua"]:35: in function `new'
[string "@Interface\AddOns\CovenantMissionHelper\CovenantMissionHelper.lua"]:52: in function `findBestDisposition'
[string "@Interface\AddOns\CovenantMissionHelper\UI.lua"]:94: in function <Interface\AddOns\CovenantMissionHelper\UI.lua:93>

Locals: self = <table> {
 checkMissionOver = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:186
 Errors = <table> {
 }
 constructResultString = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:382
 getTargetIndexes = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:410
 simulate = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:123
 onUnitTakeDamage = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:328
 getTurnOrder = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:227
 isTargetableUnit = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:214
 new = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:38
 makeUnitAction = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:253
 CombatLogEvents = <table> {
 }
 getTargetableUnits = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:218
 __index = <table> {
 }
 HiddenCombatLog = <table> {
 }
 getTotalLostHP = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:336
 isWin = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:401
 CombatLog = <table> {
 }
 getMyTeam = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:353
 manageBuffsFromDeadUnits = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:316
 fight = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:145
 manageAppliedBuffs = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:302
 setHasRandomSpells = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:169
 isUnitAlive = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:206
}
missionPage = <unnamed> {
 UpdatePortraitPulse = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_CovenantMissionUI.lua:964
 EnemyBackground = <unnamed> {
 }
 missionEffects = <table> {
 }
 0 = <userdata>
 StartMissionFrame = <unnamed> {
 }
 EmptyString = <unnamed> {
 }
 CostFrame = <unnamed> {
 }
 mentorLevel = 0
 lastUpdate = 2735.089000
 CheckCounter = <function> defined @Interface\AddOns\Blizzard_GarrisonTemplates\Blizzard_GarrisonMissionTemplates.lua:2322
 GetFollowerFrameFromID = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1384
 Median = <unnamed> {
 }
 CalculateDurabilityLoss = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1432
 missionInfo = <table> {
 }
 SetFollowerListSortFuncsForMission = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1356
 mentorItemLevel = 0
 AddFollower = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_CovenantMissionUI.lua:948
 StartMissionButton = <unnamed> {
 }
 NineSlice = <unnamed> {
 }
 Board = <unnamed> {
 }
 FollowerBackground = <unnamed> {
 }
 SetCounters = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1352
 ItemLevelHitboxFrame = <unnamed> {
 }
 GenerateSuccessTooltip = <function> defined @Interface\AddOns\Blizzard_GarrisonTemplates\Blizzard_GarrisonMissionTemplates.lua:2318
 BoardDropShadow = <unnamed> {
 }
 CloseButton = <unnamed> {
 }
 IconBG = <unna

**Comment by Amaalaa** [comment]
Not sure if the same message, but this is when I add a troop (or take them away)

Message: Interface\AddOns\CovenantMissionHelper\Board.lua:99: attempt to perform arithmetic on field 'xp' (a nil value)
Time: Sun Jan 24 11:33:26 2021
Count: 5
Stack: Interface\AddOns\CovenantMissionHelper\Board.lua:99: attempt to perform arithmetic on field 'xp' (a nil value)
[string "@Interface\AddOns\CovenantMissionHelper\Board.lua"]:99: in function `new'
[string "@Interface\AddOns\CovenantMissionHelper\CovenantMissionHelper.lua"]:29: in function <...dOns\CovenantMissionHelper\CovenantMissionHelper.lua:25>
[string "@Interface\AddOns\CovenantMissionHelper\CovenantMissionHelper.lua"]:37: in function `simulateFight'
[string "@Interface\AddOns\CovenantMissionHelper\CovenantMissionHelper.lua"]:20: in function <...dOns\CovenantMissionHelper\CovenantMissionHelper.lua:15>
[string "=[C]"]: in function `UpdateAllyPower'
[string "@Interface\AddOns\Blizzard_GarrisonUI\Blizzard_CovenantMissionUI.lua"]:647: in function `AssignFollowerToMission'
[string "@Interface\AddOns\Blizzard_GarrisonUI\Blizzard_CovenantMissionUI.lua"]:472: in function `ptr'
[string "@Interface\SharedXML\CallbackRegistry.lua"]:55: in function `TriggerEvent'
[string "@Interface\AddOns\Blizzard_GarrisonUI\Blizzard_AdventuresPuck.lua"]:426: in function <...dOns\Blizzard_GarrisonUI\Blizzard_AdventuresPuck.lua:423>

Locals: self = <table> {
 checkMissionOver = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:186
 Errors = <table> {
 }
 constructResultString = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:382
 getTargetIndexes = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:410
 simulate = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:123
 onUnitTakeDamage = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:328
 getTurnOrder = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:227
 isTargetableUnit = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:214
 new = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:38
 makeUnitAction = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:253
 CombatLogEvents = <table> {
 }
 getTargetableUnits = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:218
 __index = <table> {
 }
 HiddenCombatLog = <table> {
 }
 getTotalLostHP = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:336
 isWin = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:401
 CombatLog = <table> {
 }
 getMyTeam = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:353
 manageBuffsFromDeadUnits = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:316
 fight = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:145
 manageAppliedBuffs = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:302
 setHasRandomSpells = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:169
 isUnitAlive = <function> defined @Interface\AddOns\CovenantMissionHelper\Board.lua:206
}
missionPage = <unnamed> {
 UpdatePortraitPulse = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_CovenantMissionUI.lua:964
 EnemyBackground = <unnamed> {
 }
 missionEffects = <table> {
 }
 0 = <userdata>
 StartMissionFrame = <unnamed> {
 }
 EmptyString = <unnamed> {
 }
 CostFrame = <unnamed> {
 }
 mentorLevel = 0
 lastUpdate = 3191.907000
 CheckCounter = <function> defined @Interface\AddOns\Blizzard_GarrisonTemplates\Blizzard_GarrisonMissionTemplates.lua:2322
 GetFollowerFrameFromID = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1384
 Median = <unnamed> {
 }
 CalculateDurabilityLoss = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1432
 missionInfo = <table> {
 }
 SetFollowerListSortFuncsForMission = <function> defined @Interface\AddOns\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:1356
 mentorIte

**Comment by Kreolix** [comment]
Fixed in v3.0.1 #18
