### ISSUE TITLE
LUA Error when adding Venthyr Troops

### ISSUE THREAD

**Issue by Threads09** [Kreolix/CovenantMissionHelper#22]
![WoWScrnShot_012521_091359](https://user-images.githubusercontent.com/1922402/105724758-d2184c80-5eed-11eb-8d32-6fc08343dd8b.jpg)

**Comment by Kreolix** [comment]
@Threads09 Hi! Are you using last version of addon? 3.0.1.

**Comment by Threads09** [comment]
I manually installed v3.0.2 this morning and it's working great, not seeing the issue anymore. Awesome addon, thank you!

**Comment by Kreolix** [comment]
Fixed
