### ISSUE TITLE
Addon isn't working after 01/29 patch at least for Night Fae

### ISSUE THREAD

**Issue by Galthariel** [Kreolix/CovenantMissionHelper#25]
Night Fae here. Something happened after Blizz patch today. No matter what companion I choose, CovenantMissionHelper is telling me I'm going to be defeated. Even easy level 38 Missions. No matter if Use Dreamweaver or Te'zan both Level 40 with 4 Trappers. And I know I already completed those missions several times with lower level Companions.

**Comment by meltmaex** [comment]
same here fae, they nerf the troops or they increased the damage from the mission, but I cant win a single mission since a few day, but...wining mission with 10/20lvl + was pretty easy with only one champion

**Comment by Kazlehoff** [comment]
not an addon bug.

Blizzard fixed trappers to only reduce damage for one turn as was initially intended.

**Comment by Kreolix** [comment]
fixed
